#!/bin/bash

function mkfiles {
    mkdir files
    for i in `seq 1 5`;
    do
		touch files/file$i.txt
	done
	insmod ./intercept.o filepath="files/file1.txt"
}
mkfiles $1
for m in `seq 2 5`;
do
    ./a.out "files/file$m.txt" "1" $((m - 1))
done
./a.out "files/file1.txt" "0" "5"
rmmod intercept
rm -rf files
cat out.txt
rm -f out.txt